### PR TITLE
A Html page maker using python

### PR DESCRIPTION
**Pull request by Nageshbansal**
Name : Nagesh Bansal
College : IIT ROORKEE

### CODE REVIEW

**Comment by mayankchaudhary26** [comment]
- Use capital letters for the starting alphabet and appropriate language extensions like: (Snake game.py), (Calculator.cpp), (Bubble sort.java)

- Provide your details (Name, College/School/Work) while making a PR.

**Comment by Nageshbansal** [comment]
What do you mean by "Starting alphabet"?

**Comment by Nageshbansal** [comment]
@mayankchaudhary26
I have made changes accordingly to your comment
Thanks

**Comment by mayankchaudhary26** [comment]
Changes are fine. But this program is just giving output as:
<html>
</html>


If this is running fine, please attach a screenshot here.

**Comment by Nageshbansal** [comment]
This program will create a html file  named as test.html
image
@mayankchaudhary26

**Comment by Nageshbansal** [comment]
hey!!! @mayankchaudhary26  can you pls check this out  and merge it 
asap...
Thanks

**Pull request merged**
