### PR TITLE
added a Dice program which was made using Python and Turtle

### PR DESCRIPTION
**Pull request by Rudra50000**
Hi! I am Rudraneel Mandal. I study in Garden High School and I am 11 years old. I have created a Dice program using Python and Turtle.

### CODE REVIEW

**Comment by mayankchaudhary26** [comment]
Are you kidding me. You can't be just a 11 year old kid.

**Comment by Rudra50000** [comment]
Thanks! :D

**Comment by Rudra50000** [comment]
> Are you kidding me. You can't be just a 11 year old kid.

I really am 11 years old. Well I will become 11 on 19th October.

**Comment by Rudra50000** [comment]
So I am currently 10 years.

**Pull request merged**
